import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from '../components/shared/Navbar';
import Footer from '../components/shared/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        {/* Adding Tidio script */}
        <script src="//code.tidio.co/pk58lx9jlyancqkbbbrqw6qubmy5jtm1.js" async></script>
      </body>
    </html>
  );
}
